language: java
jdk: 
  - openjdk12
script:
  - ./gradlew build --info
deploy:
  provider: heroku
  api_key: $API_KEY
  app:
    master: jalp-staging
    production: jalp-production
after_success:
  - ./gradlew jacocoTestReport coveralls